#!/usr/bin/env bash
# Install and configure nginx server with basic homepage and custom 404 error page
FILE="/etc/nginx/sites-available/default"

# Install server
sudo apt-get update -y
sudo apt-get install nginx -y

# Add custom header
sudo sed -i "37iadd_header X-Served-By: $HOSTNAME;" $FILE

#restart nginx service
sudo service nginx restart
