#!/bin/bash -e
## Script to make file executable, streamline git commits, and check lines for Holberton systems projects
##
##Usage: ./commit <FILENAME> "<COMMIT COMMENT>" 
##
##Isaac Wong
##20180110
##
##Last Update 20180110
##
##https://github.com/thirdcaptain/holberton-system_engineering-devops/blob/master/0x01-shell_permissions/commit

filename="$1"
echo "Filename is: "$filename

comment="$2"
echo "Commit comment is: "$comment

#display number of lines
#wc -l $filename

#make file executable
chmod u+x $filename

#add file, commit, and push to git
git add $filename
git commit -m "$comment"
git push

#display number of lines                                                                                               
wc -l $filename

#check if file is executable
if [[ -x "$filename" ]]
then
    echo "File '$filename' is executable"
else
    echo "File '$filename' is not executable or found"
fi
