#!/usr/bin/env bash
# Sets web server port number to 80

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart

# FILE="/etc/nginx/sites-enabled/default"

# sudo sed -i "21s/8080/80" $FILE
# sudo sed -i "22s/8080/80" $FILE

# sudo service nginx restart
