#!/usr/bin/env bash
#Script displays Holberton School 10 times using a until loop

#count=10
#until ((count == 0))
#do
#	echo "Holberton School"
#	((count--))
#done

COUNT=0
until [ $COUNT -eq 10 ]
do
    echo "Holberton School"
    let COUNT+=1
done
