#!/usr/bin/env bash
#Prints Holberton school 10 times, but for 9th interation, prints Hi on new line

i=1
while ((i <= 10))
do
    echo "Holberton School"
    if ((i == 9))
	then
	echo "Hi"
    fi
    ((i++))
done
$i
i = 5
$
