#!/usr/bin/env bash
#Prints Holberton school 10 times, but for 9th interation, prints Hi on new line

$i
for i in {1..10}
do
    echo "Holberton School"
    if ((i == 9))
	then
	echo "Hi"
    fi
done
