#!/usr/bin/env bash
#Script prints time for 12 hours and 59 minutes

hour=0
min=1
while ((hour <= 12))
do
    echo "Hour: $hour"
    min=1
    while ((min <= 59))
    do
	echo $min
	((min++))
    done
    ((hour++))
done
