#!/usr/bin/env bash
#Script that provides information about holberton file

file="holbertonschool"

if [ -e "$file" ]
   then
    echo "holbertonschool file exists"
    if [ -s "$file" ]
	then
	echo "holbertonschool file is not empty"
	if [ -f "$file" ]
	    then
	    echo "holbertonschool is a regular file"
	fi
    else
	echo "holbertonschool file is empty"
    fi
else
    echo "holbertonschool file does not exist"
fi
