#!/usr/bin/env bash
# Transfers a file from client to server using SCP
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

# Check for minimum number of arguments
if [ "$#" -lt 3 ]
    then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi

# If SSH key path is provided, 4 parameters
if [ "$#" -gt 3 ]
    then
    scp -i "$4" "$1" "$3@$2:$1"
    exit
fi

# If no SSH key path is provided, 3 parameters
scp "$1" "$3@$2:$1"
