#!/usr/bin/env bash
# Install and configure nginx server with basic homepage
sudo apt-get update -y
sudo apt-get install nginx -y
sudo bash -c 'echo "Holberton School" > /usr/share/nginx/html/index.html'
sudo service nginx start
