#!/usr/bin/env bash
# Install and configure nginx server with basic homepage
sudo apt-get update -y
sudo apt-get install nginx -y
sudo bash -c 'echo "Holberton School" > /usr/share/nginx/html/index.html'

REDIRECT='        location \/redirect_me {\n                return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n}\n'
sudo sed -i "30i$REDIRECT" /etc/nginx/sites-available/default

sudo service nginx restart
