#!/usr/bin/env bash
# Install and configure nginx server with basic homepage
sudo apt-get update -y
sudo apt-get install nginx -y
sudo bash -c 'echo "Holberton School" > /usr/share/nginx/html/index.html'
find_string='# Only for nginx-naxsi'

redirect_string='\
        location \/redirect_me {\
                return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\
}\n\
# Only for nginx-naxsi'

sudo sed -i "s/$find_string/$redirect_string/" /etc/nginx/sites-available/default
sudo service nginx restart